logging:
  level:
    com.likelion.exam.app_2022_12_19: debug
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true